version: 1.0.{build}
image: Ubuntu

install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-11-jdk
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

build_script:
  - mvn clean test

test: off

on_success:
  - echo "Tests passed!"

on_failure:
  - echo "Tests failed!"